export interface Viaje {
    chofer: string,
    partida: string,
    destino: string,
    patente: string,
    asientos: number,
    disponibles: number,
    tarifa:number,
    clientes:string[],
    estado:string,
    lat_partida: any,
    lng_partida: any,
    lat_destino: any,
    lng_destino: any,
}
